# k8s/mysql-deployment.yaml
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mx-bank-currency-exchange-mysql-pv-claim
  namespace: mx-bank
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi